version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: web3_blog_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web3blog
    volumes:
      - ./mysql-data:/var/lib/mysql
